version: "3"

services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - mongo
    environment:
      SERVER_DB_HOST: mongodb://mongo/rest-exercise-db

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
